### ISSUE TITLE
Friendmojis appear as broken pictures

### ISSUE THREAD

**Issue by ghost** [jpoles1/bitmoji#1]
I did exactly as you said, i substituted the ids, but the friendmojis won't generate, they appear as broken pictures.

**Comment by ghost** [comment]
> I did exactly as you said, i substituted the ids, but the friendmojis won't generate, they appear as broken pictures.
The ID's
https://sdk.bitmoji.com/render/panel/6ad2caa3-107d-4642-a62e-496090c94972-fe8c29c9-3c27-458d-81b6-cc726f3db863-v1.png?transparent=1&palette=1
[second link deleted]

**Comment by jpoles1** [comment]
Aight, got it figured out. Not sure where those URLs came from but they seem to include some extraneous information not related to your bitmoji ID (probably the code for the scene those bitmoji appear in). 

By extracting the last 5 segments of the IDs in those URLs I was able to get it working for ya! Just a bit of trial and error in case you're wondering how I figured it out :)

Your personal URL for those two bitmoji IDs would thus be:

https://jpoles1.github.io/bitmoji/friends.html?firstid=fe8c29c9-3c27-458d-81b6-cc726f3db863&secondid=df7c4366-4bfc-497f-9177-d79c957ed474

Enjoy and happy holidays!!

**Comment by jpoles1** [comment]
@ardpeiris could you please share where exactly you got those URLs from? Hoping you might be able to share another way to help others to figure out their own bitmoji IDs a bit easier. Thanks!

**Comment by ghost** [comment]
> @ardpeiris could you please share where exactly you got those URLs from? Hoping you might be able to share another way to help others to figure out their own bitmoji IDs a bit easier. Thanks!
Thank you so much for the help, the fixed link you gave works!
I just copied it from the bitmoji chrome extension. just like in the youtube video https://www.youtube.com/watch?v=bhBSKCd5HUQ
For privacy concerns I wish to request you to remove the second ID in the link you provided, Thank You!

**Comment by ardpeiris** [comment]
I created a video on this
https://youtu.be/U71z5qLlpeA

**Comment by ghost** [comment]
Created a video tutorial https://youtu.be/MGgIvR2bg_Q
